### ISSUE TITLE
Geographische Metadaten für Publikationen

### ISSUE THREAD

**Issue by nuest** [KFiD-G/KDSF#3]
Geographische Metadaten (_Wo und wann?_) haben ein hohes Potential wissenschaftliche Outputs zu Verknüpfen wo Schlagwörter und Volltextsuche scheitern. Sie können unzweideutige Beziehungen herstellen, analog zu persistenten Identifiern (PIDs).

Solche Geometadaten könnten auch für Publikationen im KDSF abgelegt werden.

Erste Erfahrungen hierzu wurden im Projekt OPTIMETA gemacht, siehe

> Nüst, Daniel, Yücel, Gazi, Cordts, Anette & Hauschke, Christian (2022). Enriching the scholarly metadata commons with citation metadata and spatio-temporal metadata to support responsible research assessment and research discovery. arXiv:2301.01502 [cs.DL]. **https://doi.org/10.48550/arXiv.2301.01502**

**Comment by KFiD-Geschaeftsstelle** [comment]
Vielen Dank für Ihren Hinweis. Auf welche Elemente bezieht sich Ihr Vorschlag? Geht es zum Beispiel um [Pu153](https://kerndatensatz-forschung.de/version1/spez_versionen/Spezifikationstabelle_KDSF_v1_3.html#Pu153) oder [Pu98](https://kerndatensatz-forschung.de/version1/spez_versionen/Spezifikationstabelle_KDSF_v1_3.html#Pu98)? Welchen PID würden Sie für Geometadaten empfehlen? Zum Beispiel [geonames](https://www.geonames.org/)?

**Comment by nuest** [comment]
(Ich bitte um Entschulding für die Verzögerung wegen längerer Abwesenheit.)

Ich kenne keine gute PID für Orte, außer den tatsächlichen Koordinaten.

Bzgl. `Pu98` - Ort der Konferenz: Da diese Orte fast immer einen Namen haben werden, finde ich das nicht so spannend.

So wie eine Publikation ein "Pu141 - Forschungsfeld" hat, bräuchte sie auch ein physisches Forschungsfeld in der realen Welt, zum Beispiel die Region in der Daten gesammelt wurden, die Städte in denen Personen befragt wurden, oder die Strecke die ein Reisebericht behandelt.

Aktuell sehe ich also kein Element dass eine bedeutungsvolle räumliche und zeitliche Verortung des _Themas_ einer Publikation behandelt. 

Ich hoffe das trägt zur Klärung bei.
