### ISSUE TITLE
KDSF-IDs als Grundlage von URIs?

### ISSUE THREAD

**Issue by nichtich** [KFiD-G/KDSF#4]
Gibt es einen Grund, warum die KDSF-ID nicht als Grundlage für die URIs der KDSF-Ontologie verwendet werden? Also beispielsweise `http://kerndatensatz-forschung.de/owl/Aggregationen#Be84` statt `http://kerndatensatz-forschung.de/owl/Aggregationen#Gesamtpersonal`? Das nebeneinander verschiedener Identifier ist etwas verwirrend und grundsätzlich sollten Benennungen nicht Grundlage von URIs sein.

**Comment by KFiD-Geschaeftsstelle** [comment]
Vielen Dank für Ihre Anfrage. Die Gestalt der URIs wurde im Rahmen des [Spezifikationsprojekt des KDSF (2013-2015)](https://kerndatensatz-forschung.de/index.php?id=erarbeitung) bestimmt. Leider lässt sich anhand der Protokolle nicht nachvollziehen, warum die URIs diese Form erhalten haben. Ich stimme Ihnen zu, dass es sinnvoller wäre, die KDSF-IDs zu verwenden. Allerdings gibt es diese bislang nur für das Aggregatdatenmodell. Für die Basisdaten, die zur Bildung der Aggregatdaten herangezogen werden, existieren keine KDSF-IDs. Es könnte sein, dass zum damaligen Zeitpunkt eine einheitliche Form für Basis- und Aggregatdaten angestrebt wurde, was die jetzige Form der URIs erklären würde. 

Aktuell wird in Kooperation mit der TIB – Leibniz-Informationszentrum Technik und Naturwissenschaften und Universitätsbibliothek an einer neuen Ontologie gearbeitet. Ich bringe Ihren Vorschlag gerne mit ein.
