### ISSUE TITLE
Geschlecht in OWL und XSD entspricht nicht der KDSF-Spezifikation

### ISSUE THREAD

**Issue by nichtich** [KFiD-G/KDSF#5]
Nach https://kerndatensatz-forschung.de/version1/Spezifikation_KDSF_v1_3.pdf:

> Geschlecht (Be7 bzw. Na7) (Ausprägungen: Männlich, Weiblich, Divers und Ohne Angabe)

In den Schema-Dateien wird CERIF 1.6.2 der Datentyp `cfGender__Type` verwendet, in dem folgende Werte möglich sind:

- `m` für Male=männlich 
- `f` für Female=weiblich
- `u`für unknown=Ohne Angabe

Divers ist nicht das gleiche wie Ohne Angabe, die Verwendung von `u` für divers wäre falsch. Im Idealfall wird CERIF angepasst, ansonsten muss in KDSF ein eigener Datentyp für Geschlecht eingeführt oder auf einen anderen Standard verwiesen werden.

**Comment by KFiD-Geschaeftsstelle** [comment]
Vielen Dank für Ihren wertvollen Hinweis. In der [kdsf.owl](https://github.com/KFiD-G/KDSF/commit/26f1d49a81cd95267ec9e836d4f16fba07d03eb1?diff=split) wurde mit der Version 1.3 `divers` bereits in die range von `Geschlecht` aufgenommen.

Unsere Recherche zu CERIF hat ergeben, dass [euroCRIS aktuell keine Weiterentwicklung vom CERIF XML Schema plant](https://dspacecris.eurocris.org/bitstream/11366/2255/1/Dvorak-Ivanovic_CERIF-Refactoring-Pilot-project_euroCRIS_SMM2022Nijmegen.pdf) (Folie 3). Wir werden daher einen eigenen Datentyp einführen. 

Wir als Geschäftstelle der [Kommission für Forschungsinformation in Deutschland](https://kfid-online.de/) sind sehr daran interessiert zu erfahren, wie die einzelnen Komponenten des KDSF genutzt werden, damit wir unsere Ressourcen entsprechend der Bedarfe einsetzen können. Könnten Sie kurz beschreiben, für welchen Anwendungsfall Sie das XML Schema nutzen?
